FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY iume-atelier-backend/pom.xml .
COPY iume-atelier-backend/src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=prod
ENTRYPOINT ["java", "-jar", "app.jar"]
